import { type NextRequest } from "next/server";
import { GITHUB_LANGUAGE_COLORS, getRandomColor } from "../../lib/constants";
import {
  getLanguageStats,
  parseBooleanParam,
  resolveUsername,
  type LanguageData,
} from "../../lib/githubLanguages";

const WIDTH = 760;
const HEIGHT = 420;
const CARD_PADDING = 32;
const BAR_WIDTH = 372;
const BAR_HEIGHT = 12;
const MAX_LANGUAGES = 8;

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(value < 0.01 ? 2 : 1)}%`;
}

function renderErrorSvg(message: string) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${WIDTH}" height="180" viewBox="0 0 ${WIDTH} 180" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="GitHub language stats error">
  <rect width="${WIDTH}" height="180" rx="16" fill="#0d1117"/>
  <rect x="1" y="1" width="${WIDTH - 2}" height="178" rx="15" stroke="#30363d"/>
  <text x="32" y="58" fill="#f0f6fc" font-family="Segoe UI, Ubuntu, sans-serif" font-size="24" font-weight="700">GitHub Language Stats</text>
  <text x="32" y="98" fill="#f85149" font-family="Segoe UI, Ubuntu, sans-serif" font-size="16">${escapeXml(message)}</text>
</svg>`;
}

function renderLanguageRows(languages: LanguageData[]) {
  return languages
    .slice(0, MAX_LANGUAGES)
    .map((language, index) => {
      const y = 136 + index * 34;
      const color = GITHUB_LANGUAGE_COLORS[language.name] ?? getRandomColor(language.name);
      const percent = Math.max(language.percentage * BAR_WIDTH, 2);
      return `
  <g>
    <circle cx="${CARD_PADDING + 4}" cy="${y - 4}" r="5" fill="${color}"/>
    <text x="${CARD_PADDING + 18}" y="${y}" fill="#f0f6fc" font-family="Segoe UI, Ubuntu, sans-serif" font-size="15" font-weight="600">${escapeXml(language.name)}</text>
    <text x="246" y="${y}" fill="#8b949e" font-family="Segoe UI, Ubuntu, sans-serif" font-size="14" text-anchor="end">${formatPercent(language.percentage)}</text>
    <rect x="278" y="${y - 12}" width="${BAR_WIDTH}" height="${BAR_HEIGHT}" rx="6" fill="#21262d"/>
    <rect x="278" y="${y - 12}" width="${percent.toFixed(1)}" height="${BAR_HEIGHT}" rx="6" fill="${color}"/>
  </g>`;
    })
    .join("");
}

function renderStatsSvg({
  username,
  includePrivate,
  repositoryCount,
  languages,
}: Awaited<ReturnType<typeof getLanguageStats>>) {
  const totalLanguages = languages.length;
  const scope = includePrivate ? "Public + private repositories" : "Public repositories";
  const subtitle = `${scope} · ${repositoryCount} repos · ${totalLanguages} languages`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${escapeXml(username)} GitHub language stats">
  <rect width="${WIDTH}" height="${HEIGHT}" rx="16" fill="#0d1117"/>
  <rect x="1" y="1" width="${WIDTH - 2}" height="${HEIGHT - 2}" rx="15" stroke="#30363d"/>
  <circle cx="684" cy="56" r="74" fill="#238636" opacity="0.14"/>
  <circle cx="710" cy="84" r="40" fill="#58a6ff" opacity="0.12"/>
  <text x="${CARD_PADDING}" y="52" fill="#f0f6fc" font-family="Segoe UI, Ubuntu, sans-serif" font-size="26" font-weight="800">@${escapeXml(username)}</text>
  <text x="${CARD_PADDING}" y="82" fill="#8b949e" font-family="Segoe UI, Ubuntu, sans-serif" font-size="15">${escapeXml(subtitle)}</text>
  <text x="${CARD_PADDING}" y="112" fill="#3fb950" font-family="Segoe UI, Ubuntu, sans-serif" font-size="13" font-weight="700">LANGUAGE USAGE</text>
  ${
    languages.length === 0
      ? `<text x="${CARD_PADDING}" y="180" fill="#8b949e" font-family="Segoe UI, Ubuntu, sans-serif" font-size="16">No language data available.</text>`
      : renderLanguageRows(languages)
  }
  <text x="${CARD_PADDING}" y="382" fill="#6e7681" font-family="Segoe UI, Ubuntu, sans-serif" font-size="12">Generated by github-stats</text>
</svg>`;
}

function svgResponse(svg: string, status = 200) {
  return new Response(svg, {
    status,
    headers: {
      "Content-Type": "image/svg+xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}

export async function GET(request: NextRequest) {
  const username = resolveUsername(request.nextUrl.searchParams.get("username"));
  if (!username) {
    return svgResponse(
      renderErrorSvg("A valid GitHub username is required."),
      400
    );
  }

  try {
    const includePrivate = parseBooleanParam(
      request.nextUrl.searchParams.get("include_private")
    );
    const stats = await getLanguageStats(username, includePrivate);
    return svgResponse(renderStatsSvg(stats));
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Failed to fetch GitHub language data.";
    return svgResponse(renderErrorSvg(message), 502);
  }
}
